### ISSUE TITLE
Latest  ROS-TCP-Connector package version 0.6.0 throws error

### ISSUE THREAD

**Issue by agru97** [Unity-Technologies/Robotics-Object-Pose-Estimation#49]
I wanted to upgrade the ROS TCP Connector package from v0.2.0light to the newest version v0.6.0 but now I keep getting this error:
```NullReferenceException: Object reference not set to an instance of an object
Unity.Robotics.ROSTCPConnector.RosTopicState.SendServiceRequest (Unity.Robotics.ROSTCPConnector.MessageGeneration.Message requestMessage, System.Int32 serviceId) (at Library/PackageCache/com.unity.robotics.ros-tcp-connector@7f055108f4/Runtime/TcpConnector/RosTopicState.cs:234)
Unity.Robotics.ROSTCPConnector.ROSConnection.SendServiceMessage[RESPONSE] (System.String rosServiceName, Unity.Robotics.ROSTCPConnector.MessageGeneration.Message serviceRequest) (at Library/PackageCache/com.unity.robotics.ros-tcp-connector@7f055108f4/Runtime/TcpConnector/ROSConnection.cs:310)
Unity.Robotics.ROSTCPConnector.ROSConnection.SendServiceMessage[RESPONSE] (System.String rosServiceName, Unity.Robotics.ROSTCPConnector.MessageGeneration.Message serviceRequest, System.Action`1[T] callback) (at Library/PackageCache/com.unity.robotics.ros-tcp-connector@7f055108f4/Runtime/TcpConnector/ROSConnection.cs:283)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <31c0f51ac5a24a22ba784db24f4ba023>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <ad50157ee00e45cdb3c8bd67012f8804>:0)```

**Comment by at669** [comment]
Hi, thanks for reaching out! This repository is meant to serve as an example starting point for running pose estimation with the pick-and-place workflow introduced in the [Pick-and-Place tutorial](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/pick_and_place/README.md), to be run with the verbatim instructions in this repo. A lot has [changed](https://github.com/Unity-Technologies/ROS-TCP-Connector/blob/main/com.unity.robotics.ros-tcp-connector/CHANGELOG.md) in the ROS-TCP-Connector package since v0.2.0--if you're interested in updating the package versions, I'd recommend you reference the updated [ROS–Unity Integration](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/ros_unity_integration/README.md) in your own fork of this project.

I've also filed an internal ticket for investigation on this issue. We'll let you know when there are updates.

[Ticket#: AIRO-1664]
